### ISSUE TITLE
Path not found (Steam Deck)

### ISSUE THREAD

**Issue by BamBungus** [mizztgc/infinitas-for-linux#3]
Managed to get the Launcher up and running using the script. It'll ask me for update, I click yes, and then i'll get an error window saying "Path not found".

Not just that, I can individually open the updater and settings, but whenever I exit out of them, it'll give me the same error.

**Comment by mizztgc** [comment]
I don't have a Steam Deck, so I can't really help you with this, but there are a few questions I have:
1. Are you sure you're playing in desktop mode and _not_ game mode?
2. What build of Wine are you using? Is it the build from the Arch Linux repositories, a custom build (Wine-TKG, Wine-GE, etc), or the Flatpak build?
3. Do you have any screenshots/videos of this error?

Also, I'd like to point out that I've never seen this error message appear during my testing.

**Comment by BamBungus** [comment]
To answer these questions:

1. Yes, I am on desktop mode and not gaming mode, made sure of it.
2. I am using the Wine flatpack that was available to install from the Discover software center.
(Another note is that before seeing this script, I was attempting to play Infinitas with Bottles, so that may have something to do with it)

Here are screenshots
![20240809_180512](https://github.com/user-attachments/assets/735a2837-db4a-47ab-ae80-c8f0853ca86a)
![20240809_180528](https://github.com/user-attachments/assets/ad5f72c5-e39f-4de4-8ef2-e159cbe8d1c6)

**Comment by mizztgc** [comment]
I was able to get the game to work with Flatpak Wine. It seems like this issue is because Flatpak can't access the path the game is located in. You can try to fix this by running the following, assuming you haven't moved all the files to a new prefix:

```
flatpak override org.winehq.Wine --user --filesystem=$HOME/.local/share/infinitas
flatpak override org.winehq.Wine --user --env=WINEPREFIX=$HOME/.local/share/infinitas
```

Some additional things as well:
- Set the `INFINITAS_LAUNCHER` variable within the launch script to point to `C:\\Games\\beatmania IIDX INFINITAS\\launcher\\modules\\bm2dx_launcher.exe`.
- Given you're on a Steam Deck, you should 100% set `INFINITAS_USE_GAMESCOPE` to 1, because the game doesn't like resolutions other than 1280x720 and 1920x1080.

**Comment by BamBungus** [comment]
My apologies cuz I am about to sound really stupid (my lack of experience with linux really shows)

But where do I set the INFINITAS_LAUNCHER.

And I have no idea how and where to set the gamescope thingy

**Comment by BamBungus** [comment]
Set the INFINITAS_USE_GAMESCOPE to 1 like you said. But now I get error 5-1501-0025.

Can't tell if this is a display issue, or an audio device issue.
![20240810_205720](https://github.com/user-attachments/assets/a09878f9-8414-48d1-8949-487bc8b33dcc)

**Comment by mizztgc** [comment]
Sorry for my absence. I've been rewriting this script and learning more things along the way. I've determined gamescope is a bust, and it doesn't really want to cooperate with anything Wine-related anymore, so I would suggest you just get rid of `INFINITAS_USE_GAMESCOPE`. Hopefully, some of the issues you're having are fixed in the new iteration of this script.

Also, that 5-1501-0025 error is indeed related to your display settings. It's probably due to the Steam Deck's display running at a 16:10 aspect ratio, and the game doesn't appreciate it as much. If the Steam Deck allows you to set your resolution to 1280x720, the game *should* work, given it's the minimum resolution KONAMI requires for this game.

**Comment by mizztgc** [comment]
I haven't heard back from you, so I'm just going to close this issue.
